name: ci pipeline
on:
#  push:
#    branches: [main]
  workflow_dispatch:

jobs:
    # code build job
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
            #with:
            #path: /home/ubuntu/myrepo
          
          - name: Clean target manually
            run: rm -rf target
          
          # Snyk SAST (Static Application Security Testing)
          - name: Snyk SCA (Software Component Analysis)
            uses: snyk/actions/maven-3-jdk-17@master
            continue-on-error: true # <--- Keeps pipeline going
            env:
              SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
              JAVA_HOME: ''

          - name: SonarQube Scan (Static Application Security Testing)
            uses: SonarSource/sonarqube-scan-action@v8.0.0
            env:
          # Authentication & Server (Best kept in Secrets)
              SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
              SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
              # Project Identification (Can be Secrets or hardcoded)
              SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
              SONAR_ORGANIZATION: ${{ secrets.SONAR_ORG_NAME }}
              # Source Code Location
              # Use 'src' for most apps, or '.' for the root directory
              SONAR_SOURCES: src 
              
            #setup java
          - name: Set up JDK 25
            uses: actions/setup-java@v4
            with:
              java-version: '25'
              distribution: 'oracle'
              cache: 'maven'

            # dependencies setup
          - name: Install dependencies
            run: |
                sudo apt install maven -y
            # check apps versions
          - name: check versions
            run: |
              java -version
              mvn -version
            
            #mvn build 
          - name: Build with maven
            run: |
              sudo rm -rf /home/runner/work/springboot-api-eks-hello/springboot-api-eks-hello/target
              echo "Current directory: $(pwd)"
              ls -la /home/runner/work/springboot-api-eks-hello/springboot-api-eks-hello
              echo "Running mvn clean install -DskipTests -e"
              mvn clean install -DskipTests -e
            
            #artifact upload 
          - name: upload artifact
            uses: actions/upload-artifact@v4
            with:
              name: springboot-api-eks-hello 
              path: target/springboot-api-eks-hello*.jar
