name: self-runner pipeline
on:
#  push:
#    branches: [main]
  workflow_dispatch:

jobs:
    # code build job
    build:
        runs-on: self-hosted
        steps:
          - uses: actions/checkout@v3
            with:
              fetch-depth: 0
            #with:
            #path: /home/ubuntu/myrepo
              
          - name: check versions
            run: |
              java -version
              mvn -version
            
            #mvn build 
          - name: remove target
            run: |
              echo "Current directory: $(pwd)"
              echo "Current directory: $(ls -la)"

            #artifact upload 
          - name: upload artifact
            uses: actions/upload-artifact@v4
            with:
              name: springboot-api-eks-hello 
              path: target/springboot-api-eks-hello*.jar

              
